### PR TITLE
Update dapp favicon to Potion logo

### LINKED ISSUE #8: Change website icon
Minor issue

Need to change website favicon for the potion Logo

Thanks

### PR DESCRIPTION
**Pull request by 0xmichalis**
Update dapp favicon from default Vue to https://github.com/potiondao/potion.fi/blob/main/assets/images/logo_icon.svg 

Fixes https://github.com/potiondao/potion-protocol-source/issues/8

### CODE REVIEW

**Comment by bonustrack** [comment]
Thanks @kargakis. How did you get this icon, is it the official one? I'm thinking the original Potion logo might be better here

**Comment by 0xmichalis** [comment]
@bonustrack frankly I don't remember how I got this logo. Which one is the official one? https://github.com/potiondao/potion.fi/blob/main/assets/images/logo_icon.svg ? Feel free to link it here and I can update the PR.

**Comment by bonustrack** [comment]
@kargakis Yes that's the one!

**Comment by 0xmichalis** [comment]
@bonustrack updated, ptal

**Review by bonustrack — APPROVED** [review]
Looks great now!

**Pull request merged**
